'use strict';
const D=window.LifeDashData, Live=window.LifeDashLive;
const $=(q,r=document)=>r.querySelector(q), $$=(q,r=document)=>[...r.querySelectorAll(q)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const id=(p='item')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const iso=()=>new Date().toISOString();const day=x=>x?String(x).slice(0,10):'';
const CURRENCIES=['EUR','MKD','RSD','BAM','BGN','ALL','USD','GBP','CHF'];
const COUNTRIES=[['DE','Germany'],['MK','North Macedonia'],['RS','Serbia'],['BA','Bosnia & Herzegovina'],['HR','Croatia'],['SI','Slovenia'],['ME','Montenegro'],['AL','Albania'],['BG','Bulgaria'],['GR','Greece'],['RO','Romania'],['AT','Austria'],['CH','Switzerland'],['IT','Italy'],['FR','France'],['XK','Kosovo'],['US','United States'],['GB','United Kingdom']];
const LANGUAGES=[['en','English'],['de','Deutsch'],['mk','Македонски'],['sr','Srpski'],['hr','Hrvatski'],['bs','Bosanski'],['sl','Slovenščina'],['sq','Shqip'],['bg','Български'],['el','Ελληνικά'],['ro','Română'],['it','Italiano']];
const ROUTES={dashboard:'Dashboard',today:'Today & Next 5 Days',notes:'Notes Pro',finance:'Finance',invoices:'Invoices',documents:'Documents',family:'Family',vehicles:'Vehicles & VIN',route:'Route Planner',explore:'Explore & Live',air:'Air Traffic',radio:'Radio',profile:'Profile & Settings'};
const KINDS=['notes','notes_settings','manual_reminders','finance_transactions','finance_bills','finance_goals','finance_utilities','vehicles','documents','family_members','family_tasks','family_shopping','family_events','travel','app_preferences'];
const state={profile:null,data:{},route:'dashboard',geo:null,map:null,mapLayers:[],deferredInstall:null,radioStations:[],radioFav:new Set(),exploreTab:'around',airScope:'50'};
const loadScript=(src,test)=>new Promise((resolve,reject)=>{if(test())return resolve();const old=document.querySelector(`script[data-runtime=\"${src}\"]`);if(old){old.addEventListener('load',resolve,{once:true});old.addEventListener('error',()=>reject(new Error('Could not load required browser library')),{once:true});return}const x=document.createElement('script');x.src=src;x.async=true;x.dataset.runtime=src;x.onload=resolve;x.onerror=()=>reject(new Error('Could not load required browser library'));document.head.appendChild(x)});
const ensureSupabase=()=>loadScript('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/dist/umd/supabase.min.js',()=>Boolean(window.supabase?.createClient));
let leafletPromise=null;const ensureLeaflet=()=>{if(window.L?.map)return Promise.resolve();if(leafletPromise)return leafletPromise;const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);leafletPromise=loadScript('https://unpkg.com/leaflet@1.9.4/dist/leaflet.js',()=>Boolean(window.L?.map));return leafletPromise};
const toast=(m,bad=false)=>{const t=$('#toast');t.textContent=m;t.style.borderColor=bad?'rgba(255,113,137,.55)':'';t.classList.add('show');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>t.classList.remove('show'),2600)};
const fmtMoney=(n,c='EUR')=>{try{return new Intl.NumberFormat(undefined,{style:'currency',currency:c||'EUR',maximumFractionDigits:2}).format(Number(n)||0)}catch{return`${Number(n||0).toFixed(2)} ${c}`}};
const fmtDate=v=>{if(!v)return'—';const d=new Date(v.length===10?`${v}T12:00:00`:v);return Number.isNaN(d.getTime())?esc(v):new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(d)};
const formData=f=>Object.fromEntries(new FormData(f).entries());
const countryOptions=(value='')=>COUNTRIES.map(([v,n])=>`<option value="${v}" ${v===value?'selected':''}>${esc(n)}</option>`).join('');
const languageOptions=(value='en')=>LANGUAGES.map(([v,n])=>`<option value="${v}" ${v===value?'selected':''}>${esc(n)}</option>`).join('');
const currencyOptions=(value='EUR')=>CURRENCIES.map(v=>`<option ${v===value?'selected':''}>${v}</option>`).join('');
function setSelects(){ $$('.country-select').forEach(s=>s.innerHTML=countryOptions(s.value||'DE'));$$('.language-select').forEach(s=>s.innerHTML=languageOptions(s.value||'en')) }
function modal(title,html,onReady){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');onReady?.($('#modalBody'))}
function closeModal(){$('#modal').classList.add('hidden');$('#modalBody').innerHTML=''}
function pageHead(title,sub='',actions=''){return`<div class="page-head"><div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><div class="page-actions">${actions}</div></div>`}
const empty=(title,body)=>`<div class="empty"><strong>${esc(title)}</strong><span>${esc(body)}</span></div>`;
function setRoute(route){route=ROUTES[route]?route:'dashboard';state.route=route;location.hash=route;$('#pageTitle').textContent=ROUTES[route];$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===route));$('.sidebar')?.classList.remove('open');render().catch(e=>{console.error(e);toast(e.message||'Could not open module',true)})}
async function reload(kind){state.data[kind]=await D.list(kind)}
async function loadAll(){$('#syncStatus').textContent='Syncing…';state.data=await D.batchLoad(KINDS);state.profile=await D.getProfile();$('#syncStatus').textContent='Synced · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});const n=state.profile?.name||D.session?.user?.email||'U';$('#avatarInitial').textContent=n.trim().charAt(0).toUpperCase()||'U';const prefs=state.data.app_preferences?.[0]||{};state.radioFav=new Set(prefs.radioFavorites||[])}
function collection(k){return Array.isArray(state.data[k])?state.data[k]:[]}
function dueItems(){const out=[];const push=(date,title,meta,route,id)=>{if(!date)return;const d=day(date);if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return;out.push({date:d,title,meta,route,id})};collection('notes').filter(x=>x.status!=='archived'&&x.status!=='completed').forEach(n=>push(n.dueDate||n.expiryDate,n.title||'Note',n.type||'note','notes',n.id));collection('finance_bills').filter(x=>!x.isPaid).forEach(x=>push(x.dueDate,x.title||'Bill',fmtMoney(x.amount,x.currency),'finance',x.id));collection('family_tasks').filter(x=>!x.done).forEach(x=>push(x.dueDate,x.title||'Family task','Family','family',x.id));collection('documents').forEach(x=>push(x.expiresAt,x.name||'Document','Expires','documents',x.id));collection('vehicles').forEach(v=>{push(v.insuranceExpires,`${v.name||v.licensePlate||'Vehicle'} insurance`,'Vehicle','vehicles',v.id);push(v.registrationExpires,`${v.name||v.licensePlate||'Vehicle'} registration`,'Vehicle','vehicles',v.id);push(v.technicalExpires,`${v.name||v.licensePlate||'Vehicle'} technical`,'Vehicle','vehicles',v.id)});return out.sort((a,b)=>a.date.localeCompare(b.date))}
function todayRange(){const now=new Date();const today=now.toISOString().slice(0,10);const end=new Date(now);end.setDate(end.getDate()+5);return{today,end:end.toISOString().slice(0,10)}}
