'use strict';
/* LifeDashPro Web enhancement layer: themes + Android-aligned Today/Next 5 timeline. */
const LD_THEMES=['dark','light','ocean','violet'];
const LD_THEME_LABELS={dark:'Dark',light:'Light',ocean:'Ocean',violet:'Violet'};
const LD_DAY_MS=86400000;
const ldPad=n=>String(n).padStart(2,'0');
function ldLocalDateISO(value=new Date()){return `${value.getFullYear()}-${ldPad(value.getMonth()+1)}-${ldPad(value.getDate())}`}
function ldNormalizeDate(value){if(!value)return undefined;if(value instanceof Date)return Number.isNaN(value.getTime())?undefined:ldLocalDateISO(value);const raw=String(value).trim();if(!raw)return undefined;const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(raw);if(m){const y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]),p=new Date(y,mo-1,d,12);return p.getFullYear()===y&&p.getMonth()===mo-1&&p.getDate()===d?`${m[1]}-${m[2]}-${m[3]}`:undefined}const p=new Date(raw);return Number.isNaN(p.getTime())?undefined:ldLocalDateISO(p)}
function ldParseDate(value){const s=ldNormalizeDate(value);if(!s)return undefined;const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d,12)}
function ldDayNumber(d){return Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/LD_DAY_MS)}
function ldDaysBetween(a,b){const x=ldParseDate(a),y=ldParseDate(b);return(!x||!y)?Infinity:ldDayNumber(y)-ldDayNumber(x)}
function ldNormalizeRecurrence(value,recurring=false){const r=String(value||'').toLowerCase().trim();if(['daily','weekly','monthly','yearly'].includes(r))return r;return recurring?'monthly':'once'}
function ldDaysInMonth(y,m){return new Date(y,m+1,0).getDate()}
function ldMonthly(anchor,y,m){return new Date(y,m,Math.min(anchor.getDate(),ldDaysInMonth(y,m)),12)}
function ldYearly(anchor,y){const m=anchor.getMonth();return new Date(y,m,Math.min(anchor.getDate(),ldDaysInMonth(y,m)),12)}
function ldNextOccurrence(anchorDate,recurrence='once',from=ldLocalDateISO()){const anchor=ldParseDate(anchorDate),start=ldParseDate(from);if(!anchor||!start)return undefined;const r=ldNormalizeRecurrence(recurrence);if(r==='once')return anchor>=start?ldLocalDateISO(anchor):undefined;if(start<=anchor)return ldLocalDateISO(anchor);if(r==='daily')return ldLocalDateISO(start);if(r==='weekly'){const elapsed=ldDayNumber(start)-ldDayNumber(anchor),offset=(7-(elapsed%7))%7,c=new Date(start);c.setDate(c.getDate()+offset);return ldLocalDateISO(c)}if(r==='monthly'){let c=ldMonthly(anchor,start.getFullYear(),start.getMonth());if(c<start){const nm=(start.getMonth()+1)%12,ny=start.getMonth()===11?start.getFullYear()+1:start.getFullYear();c=ldMonthly(anchor,ny,nm)}return ldLocalDateISO(c)}let c=ldYearly(anchor,start.getFullYear());if(c<start)c=ldYearly(anchor,start.getFullYear()+1);return ldLocalDateISO(c)}
function ldResolveUpcoming({date,recurrence,recurring=false,completed=false,archived=false,horizonDays=5,today=ldLocalDateISO()}){if(completed||archived)return null;const anchor=ldNormalizeDate(date);if(!anchor)return null;const r=ldNormalizeRecurrence(recurrence,recurring),occ=ldNextOccurrence(anchor,r,today);if(!occ)return null;const diff=ldDaysBetween(today,occ);return diff>=0&&diff<=Math.max(0,horizonDays)?{date:occ,daysUntil:diff,recurrence:r}:null}
function ldTheme(){return LD_THEMES.includes(localStorage.getItem('lifedash_web_theme'))?localStorage.getItem('lifedash_web_theme'):'dark'}
function ldApplyTheme(theme){const t=LD_THEMES.includes(theme)?theme:'dark';document.documentElement.dataset.theme=t;localStorage.setItem('lifedash_web_theme',t);const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=t==='light'?'#f5f7fb':t==='violet'?'#24143f':t==='ocean'?'#062537':'#1a1f5c';const btn=document.getElementById('themeCycleBtn');if(btn){btn.textContent=t==='light'?'☀':t==='ocean'?'≈':t==='violet'?'◆':'◐';btn.title=`Theme: ${LD_THEME_LABELS[t]}`}}
function ldPrefs(){const rows=collection('app_preferences');return rows.find(x=>x.id==='main')||rows[0]||{id:'main'}}
async function ldSaveTheme(theme){const t=LD_THEMES.includes(theme)?theme:'dark';ldApplyTheme(t);try{const prefs={...ldPrefs(),id:'main',webTheme:t,updatedAt:iso()};await D.upsert('app_preferences',prefs);await reload('app_preferences');toast(`${LD_THEME_LABELS[t]} theme saved`)}catch(e){toast('Theme changed on this browser; cloud preference could not sync',true)}if(state.route==='profile')render()}
function ldCycleTheme(){const current=document.documentElement.dataset.theme||ldTheme(),i=LD_THEMES.indexOf(current);void ldSaveTheme(LD_THEMES[(i+1)%LD_THEMES.length])}

dueItems=function(){
  const out=[],today=ldLocalDateISO();
  const add=({date,title,meta,route,id,icon='📅',source='other',time,recurrence='once',recurring=false,completed=false,archived=false,overdue=true})=>{
    const anchor=ldNormalizeDate(date);if(!anchor||completed||archived)return;
    const rec=ldNormalizeRecurrence(recurrence,recurring),resolved=ldResolveUpcoming({date:anchor,recurrence:rec,horizonDays:5,today});
    if(resolved){out.push({date:resolved.date,title,meta,route,id,icon,source,time,recurrence:rec,daysUntil:resolved.daysUntil,overdue:false});return}
    if(overdue&&rec==='once'){const diff=ldDaysBetween(today,anchor);if(diff<0&&diff>=-30)out.push({date:anchor,title,meta,route,id,icon,source,time,recurrence:rec,daysUntil:diff,overdue:true})}
  };
  collection('notes').forEach(n=>add({date:n.dueDate||n.expiryDate,title:n.type==='invoice'?`Invoice: ${n.title||'Invoice'}`:n.title||'Note',meta:n.type==='invoice'?(n.amount?fmtMoney(n.amount,n.currency||'EUR'):'Invoice'):(n.category||n.type||'Note'),route:n.type==='invoice'?'invoices':'notes',id:n.id,icon:n.type==='invoice'?'🧾':'📝',source:n.type==='invoice'?'invoice':'notes',time:n.dueTime,completed:n.status==='completed',archived:n.status==='archived'}));
  collection('finance_transactions').filter(x=>!['notes','invoice'].includes(String(x.sourceModule||''))).forEach(x=>add({date:x.dueDate||x.date,title:x.description||'Finance',meta:`${x.type==='income'?'Income':'Expense'} · ${fmtMoney(x.amount,x.currency||'EUR')}`,route:'finance',id:x.id,icon:'💳',source:'finance',time:x.time,recurrence:x.periodicity||'once',completed:!!x.isPaid&&!!x.dueDate&&x.periodicity==='once'}));
  collection('finance_bills').forEach(x=>add({date:x.dueDate,title:x.title||'Bill',meta:fmtMoney(x.amount,x.currency||'EUR'),route:'finance',id:x.id,icon:'🧾',source:'finance',recurring:!!x.recurring,completed:!!x.isPaid}));
  collection('family_tasks').forEach(x=>add({date:x.dueDate,title:x.title||'Family task',meta:x.assignedTo||'Family',route:'family',id:x.id,icon:'✅',source:'family',time:x.reminderTime,completed:!!x.done}));
  collection('documents').forEach(x=>add({date:x.expiresAt,title:x.name||'Document',meta:'Document expiry',route:'documents',id:x.id,icon:'📄',source:'document'}));
  collection('vehicles').forEach(v=>{const n=v.name||[v.brand,v.model].filter(Boolean).join(' ')||v.licensePlate||'Vehicle';add({date:v.registrationExpires,title:`${n}: registration`,meta:'Vehicle',route:'vehicles',id:`${v.id}-reg`,icon:'🚗',source:'vehicle'});add({date:v.insuranceExpires,title:`${n}: insurance`,meta:'Vehicle',route:'vehicles',id:`${v.id}-ins`,icon:'🛡️',source:'vehicle'});add({date:v.technicalExpires,title:`${n}: technical`,meta:'Vehicle',route:'vehicles',id:`${v.id}-tech`,icon:'🔧',source:'vehicle'})});
  collection('family_members').forEach(m=>add({date:m.birthday,title:`Birthday: ${m.name||'Family member'}`,meta:m.relation||'Birthday',route:'family',id:m.id,icon:'🎂',source:'birthday',recurrence:'yearly',overdue:false}));
  collection('family_events').forEach(e=>add({date:e.date||e.dueDate,title:e.title||'Family event',meta:e.type||'Family event',route:'family',id:e.id,icon:e.type==='birthday'?'🎂':'📅',source:'family',recurrence:e.type==='birthday'?'yearly':e.recurrence||'once'}));
  collection('travel').forEach(t=>add({date:t.startDate,title:`Trip: ${t.destination||t.country||'Travel'}`,meta:t.country||'Travel',route:'route',id:t.id,icon:'✈️',source:'travel'}));
  collection('manual_reminders').forEach(r=>add({date:r.date,title:r.title||'Reminder',meta:r.type||'Reminder',route:'today',id:r.id,icon:'🔔',source:'reminder',time:r.time,completed:!!r.done}));
  return out.sort((a,b)=>`${a.date} ${a.time||''}`.localeCompare(`${b.date} ${b.time||''}`));
};
todayRange=function(){const n=new Date(),end=new Date(n);end.setDate(end.getDate()+5);return{today:ldLocalDateISO(n),end:ldLocalDateISO(end)}};

todayPage=function(){const{today,end}=todayRange(),all=dueItems(),todayRows=all.filter(x=>x.date===today&&!x.overdue),next=all.filter(x=>x.date>today&&x.date<=end&&!x.overdue),past=all.filter(x=>x.overdue).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10);const line=(rows,emptyTitle,emptyBody)=>rows.length?rows.map(i=>`<div class="timeline-item timeline-${esc(i.source)}"><time>${i.date===today?'TODAY':fmtDate(i.date)}${i.time?`<small>${esc(i.time)}</small>`:''}</time><div><b>${esc(i.icon)} ${esc(i.title)}</b><span>${esc(i.meta)}${i.recurrence&&i.recurrence!=='once'?` · ${esc(i.recurrence)}`:''}</span><button class="mini-btn" data-go="${esc(i.route)}">Open</button></div></div>`).join(''):empty(emptyTitle,emptyBody);return`${pageHead('Today & Next 5 Days','Android-aligned timeline: notes, invoices, finance, family, birthdays, documents, vehicles, travel and reminders.',`<button class="quiet" data-refresh>↻ Sync now</button>`)}<div class="today-summary"><span class="pill ${todayRows.length?'warn':'good'}">${todayRows.length} today</span><span class="pill">${next.length} next 5 days</span><span class="pill ${past.length?'bad':''}">${past.length} overdue shown</span></div><div class="grid"><div class="card span-6"><h3>Today</h3><span class="card-sub">Items due on your local calendar date</span><div class="timeline">${line(todayRows,'Nothing due today','Your synced LifeDashPro timeline is clear for today.')}</div></div><div class="card span-6"><h3>Next 5 days</h3><span class="card-sub">Recurring items are resolved to their next occurrence</span><div class="timeline">${line(next,'No upcoming items','Nothing is due during the next five days.')}</div></div>${past.length?`<div class="card full"><h3>Recently overdue</h3><span class="card-sub">One-time items from the last 30 days</span><div class="timeline">${line(past,'No overdue items','')}</div></div>`:''}</div>`};

const ldOriginalProfilePage=profilePage;
profilePage=function(){const html=ldOriginalProfilePage();const t=document.documentElement.dataset.theme||ldTheme();const card=`<div class="settings-card theme-settings"><h3>Appearance</h3><p class="card-sub">Choose a Web theme. The preference is saved to your LifeDashPro account.</p><div class="theme-grid">${LD_THEMES.map(x=>`<button type="button" class="theme-choice ${t===x?'active':''}" data-theme-choice="${x}"><i class="theme-preview theme-preview-${x}"></i><b>${LD_THEME_LABELS[x]}</b><span>${x==='dark'?'Current dark look':x==='light'?'Bright workspace':x==='ocean'?'Deep blue & cyan':'Purple night'}</span></button>`).join('')}</div></div>`;const i=html.lastIndexOf('</div>');return i<0?html:html.slice(0,i)+card+html.slice(i)};

const ldOriginalBindPage=bindPage;
bindPage=function(){ldOriginalBindPage();if(state.route==='profile')$$('[data-theme-choice]',$('#page')).forEach(b=>b.onclick=()=>ldSaveTheme(b.dataset.themeChoice))};
const ldOriginalLoadAll=loadAll;
loadAll=async function(){await ldOriginalLoadAll();const prefs=ldPrefs();state.radioFav=new Set(prefs.radioFavorites||[]);ldApplyTheme(prefs.webTheme||ldTheme())};

toggleRadioFav=async function(sid){state.radioFav.has(sid)?state.radioFav.delete(sid):state.radioFav.add(sid);const prefs={...ldPrefs(),id:'main',radioFavorites:[...state.radioFav],updatedAt:iso()};try{await D.upsert('app_preferences',prefs);await reload('app_preferences');toast('Radio favorites synced');if(state.route==='radio')loadRadio()}catch(e){toast(e.message,true)}};

document.addEventListener('DOMContentLoaded',()=>{ldApplyTheme(ldTheme());const host=document.querySelector('.top-actions'),notify=document.getElementById('notifyBtn');if(host&&notify&&!document.getElementById('themeCycleBtn')){const b=document.createElement('button');b.id='themeCycleBtn';b.className='icon-btn';b.type='button';b.setAttribute('aria-label','Change theme');b.onclick=ldCycleTheme;host.insertBefore(b,notify);ldApplyTheme(ldTheme())}});
