(()=>{
'use strict';
const params=new URLSearchParams(location.search);if(params.get('workspace')!=='desktop')return;
const KEY='lifedash_internal_apps_theme_v2';
const ROUTES=new Set(['today','notes','finance','invoices','documents','family','vehicles','route','explore','air','radio','profile']);
const labels={today:'Today',notes:'Notes Pro',finance:'Finance',invoices:'Invoices',documents:'Documents',family:'Family',vehicles:'Vehicles',route:'Route Planner',explore:'Explore & Live',air:'Air Traffic',radio:'Balkan Vibes',profile:'Profile'};
const safeCollection=k=>{try{return typeof collection==='function'?(collection(k)||[]):[]}catch{return[]}};
const localDay=(v=new Date())=>{const d=v instanceof Date?v:new Date(v);if(Number.isNaN(d.getTime()))return'';return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const daysUntil=v=>{if(!v)return Infinity;const s=String(v).slice(0,10),m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(s);if(!m)return Infinity;const a=new Date(),b=new Date(+m[1],+m[2]-1,+m[3]);a.setHours(0,0,0,0);b.setHours(0,0,0,0);return Math.round((b-a)/86400000)};
const money=(n,c)=>{try{return typeof fmtMoney==='function'?fmtMoney(Number(n||0),c||state?.profile?.currency||'EUR'):`${Number(n||0).toFixed(2)} ${c||'EUR'}`}catch{return String(n||0)}};
const theme=()=>localStorage.getItem(KEY)==='night'?'night':'day';
function applyTheme(v,save=true){v=v==='night'?'night':'day';document.body.dataset.appWindowTheme=v;if(save)localStorage.setItem(KEY,v);document.querySelectorAll('[data-app2-theme]').forEach(b=>b.classList.toggle('active',b.dataset.app2Theme===v));}
function installThemeSwitch(){const bar=document.querySelector('#desktopWindow .desktop-window-titlebar');if(!bar)return;bar.querySelectorAll('.window-theme-switch,.modal-window-theme').forEach(x=>x.remove());if(bar.querySelector('.app2-theme-switch'))return;const controls=bar.querySelector('.window-controls');if(!controls)return;controls.insertAdjacentHTML('beforebegin',`<div class="app2-theme-switch" aria-label="Application theme"><button type="button" data-app2-theme="day">☀ Day</button><button type="button" data-app2-theme="night">☾ Night</button></div>`);applyTheme(theme(),false)}
function stat(label,value,tone='',small=''){return `<div class="app2-stat ${tone}"><span>${label}</span><strong>${value}</strong>${small?`<small>${small}</small>`:''}</div>`}
function metrics(route){
 const today=localDay(),month=today.slice(0,7);
 if(route==='today'){let all=[];try{all=typeof dueItems==='function'?dueItems():[]}catch{}const t=all.filter(x=>x.date===today&&!x.overdue).length,n=all.filter(x=>x.date>today&&!x.overdue).length,o=all.filter(x=>x.overdue).length;return[stat('Due today',t,t?'warn':'good'),stat('Upcoming',n,'accent','next 5 days'),stat('Overdue',o,o?'bad':'good')];}
 if(route==='notes'){const a=safeCollection('notes').filter(x=>x.status!=='archived'),due=a.filter(x=>{const d=daysUntil(x.dueDate||x.expiryDate);return d>=0&&d<=7}).length,inv=a.filter(x=>x.type==='invoice').length,atts=a.reduce((s,x)=>s+(Array.isArray(x.attachments)?x.attachments.length:0),0);return[stat('Active notes',a.length),stat('Due soon',due,due?'warn':''),stat('Invoices',inv,'accent'),stat('Attachments',atts)];}
 if(route==='finance'){const tx=safeCollection('finance_transactions'),m=tx.filter(x=>String(x.date||'').slice(0,7)===month),inc=m.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.baseAmountAtEntry??x.amount??0),0),exp=m.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.baseAmountAtEntry??x.amount??0),0),b=safeCollection('finance_bills').filter(x=>!x.isPaid);return[stat('Monthly balance',money(inc-exp),inc-exp>=0?'good':'bad'),stat('Income',money(inc),'good'),stat('Expenses',money(exp),'bad'),stat('Unpaid bills',b.length,b.length?'warn':'good')];}
 if(route==='invoices'){const a=safeCollection('notes').filter(x=>x.type==='invoice'),paid=a.filter(x=>x.isPaid||x.status==='completed'||x.invoice?.status==='paid'),open=a.length-paid.length,total=a.reduce((s,x)=>s+Number(x.amount||0),0);return[stat('Invoices',a.length),stat('Paid',paid.length,'good'),stat('Open',open,open?'warn':'good'),stat('Total value',money(total,a[0]?.currency||state?.profile?.currency||'EUR'),'accent')];}
 if(route==='documents'){const a=safeCollection('documents'),cloud=a.filter(x=>x.storagePath||x.attachments?.some?.(y=>y.storagePath)).length,soon=a.filter(x=>{const d=daysUntil(x.expiresAt);return d>=0&&d<=45}).length;return[stat('Documents',a.length),stat('Cloud files',cloud,'accent'),stat('Expiring soon',soon,soon?'warn':'good')];}
 if(route==='family'){const m=safeCollection('family_members'),t=safeCollection('family_tasks'),s=safeCollection('family_shopping'),e=safeCollection('family_events');return[stat('Members',m.length),stat('Open tasks',t.filter(x=>!x.done).length,'accent'),stat('Shopping',s.filter(x=>!x.checked).length,'warn'),stat('Events',e.length)];}
 if(route==='vehicles'){const a=safeCollection('vehicles'),soon=a.filter(v=>[v.registrationExpires,v.insuranceExpires,v.technicalExpires].some(x=>{const d=daysUntil(x);return d>=0&&d<=60})).length,svc=a.reduce((s,v)=>s+(Array.isArray(v.services)?v.services.length:0),0),vin=a.filter(v=>v.vin).length;return[stat('Vehicles',a.length),stat('Expiring',soon,soon?'warn':'good','next 60 days'),stat('Service records',svc,'accent'),stat('VIN stored',vin)];}
 if(route==='route'){const trips=safeCollection('travel'),up=trips.filter(x=>daysUntil(x.startDate)>=0).length;return[stat('Saved trips',trips.length),stat('Upcoming trips',up,'accent'),stat('Route modes','Car · Walk · Bike'),stat('Optimization','Multi-stop','good')];}
 if(route==='explore'){return[stat('Around me','OSM','accent'),stat('Safety','Live','good'),stat('Road','Traffic'),stat('Maritime','AIS')];}
 if(route==='air'){const scope=state?.airScope||'50';return[stat('Scope',`${scope} km`,'accent'),stat('Provider','OpenSky'),stat('Map','Live radar','good')];}
 if(route==='radio'){const fav=state?.radioFav?.size||0,loaded=Array.isArray(state?.radioStations)?state.radioStations.length:0,a=document.getElementById('audio'),playing=Boolean(a&&!a.paused&&a.src);return[stat('Favorites',fav,'accent'),stat('Loaded stations',loaded),stat('Player',playing?'Playing':'Ready',playing?'good':''),stat('Experience','Balkan Vibes')];}
 if(route==='profile'){return[stat('Country',state?.profile?.country||'—'),stat('Language',state?.profile?.language||'—'),stat('Currency',state?.profile?.currency||'EUR','accent'),stat('Cloud sync','Connected','good')];}
 return[];
}
function wrapTables(page){page.querySelectorAll('table.data-table').forEach(t=>{if(t.parentElement?.classList.contains('app2-table-wrap'))return;const w=document.createElement('div');w.className='app2-table-wrap';t.parentNode.insertBefore(w,t);w.appendChild(t)})}
function labelSections(page,route){const map={notes:'Notes library',invoices:'Invoice register',documents:'Document library'};if(!map[route])return;const card=[...page.querySelectorAll('.card')].find(c=>c.querySelector('.data-table'));if(!card||card.querySelector('.app2-section-title'))return;card.insertAdjacentHTML('afterbegin',`<div class="app2-section-title"><b>${map[route]}</b><span>${route==='notes'?'Search, open, edit and manage synced notes.':route==='invoices'?'All synced invoice records in one place.':'Private records and cloud attachments.'}</span></div>`)}
function decorate(){const page=document.getElementById('page'),win=document.getElementById('desktopWindow');if(!page||!win)return;const route=(location.hash||'#dashboard').slice(1)||'dashboard';const active=ROUTES.has(route)&&!win.classList.contains('hidden');document.body.classList.toggle('internal-apps-v2-active',active);if(!active){page.classList.remove('app2-page');delete page.dataset.app2Route;return}installThemeSwitch();applyTheme(theme(),false);page.classList.add('app2-page');page.dataset.app2Route=route;const head=page.querySelector('.page-head');if(head&&!page.querySelector('.app2-overview')){const m=metrics(route);if(m.length)head.insertAdjacentHTML('afterend',`<section class="app2-overview" style="--app2-count:${m.length}">${m.join('')}</section>`)}wrapTables(page);labelSections(page,route)}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate()})}
function init(){document.body.classList.add('internal-apps-v2');applyTheme(theme(),false);installThemeSwitch();document.addEventListener('click',e=>{const b=e.target.closest('[data-app2-theme]');if(!b)return;e.preventDefault();e.stopPropagation();applyTheme(b.dataset.app2Theme)});const page=document.getElementById('page');if(page)new MutationObserver(schedule).observe(page,{childList:true,subtree:true});const win=document.getElementById('desktopWindow');if(win)new MutationObserver(schedule).observe(win,{attributes:true,attributeFilter:['class']});window.addEventListener('hashchange',schedule);schedule()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
