(()=>{
'use strict';
if(new URLSearchParams(location.search).get('workspace')!=='desktop')return;
const LOC_KEY='lifedash_web_location_v37_17';
const FIN_KEY='lifedash_web_finance_month';
const nowDay=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const monthNow=()=>nowDay().slice(0,7);
const validPoint=p=>p&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lon))&&Math.abs(Number(p.lat))<=90&&Math.abs(Number(p.lon))<=180&&!(Number(p.lat)===0&&Number(p.lon)===0);
const prefs=()=>{try{return collection('app_preferences')[0]||{id:'main'}}catch{return{id:'main'}}};
async function reverseGeo(lat,lon){try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}&format=jsonv2&zoom=10&addressdetails=1`,{headers:{Accept:'application/json','Accept-Language':'en'}});if(!r.ok)return null;const j=await r.json(),a=j.address||{};return{city:a.city||a.town||a.village||a.municipality||a.county||'',country:String(a.country_code||'').toUpperCase()}}catch{return null}}
async function persistLocation(point,source='web-gps'){
 if(!validPoint(point))return point;
 const geo=await reverseGeo(Number(point.lat),Number(point.lon));
 const old=prefs(),value={...old,id:'main',homeCity:geo?.city||old.homeCity||state.profile?.city||'',country:geo?.country||old.country||state.profile?.country||'',lat:Number(point.lat),lon:Number(point.lon),locationMode:source.includes('gps')?'gps':old.locationMode||'profile',lastLocationSource:source,lastLocationDevice:'web',lastLocationUpdatedAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
 try{await D.upsert('app_preferences',value);await reload('app_preferences')}catch{}
 try{localStorage.setItem(LOC_KEY,JSON.stringify(value))}catch{}
 return{lat:value.lat,lon:value.lon,city:value.homeCity,country:value.country,source};
}
function cloudLocation(){const p=prefs();if(validPoint(p))return{lat:Number(p.lat),lon:Number(p.lon),city:p.homeCity||state.profile?.city||'',country:p.country||state.profile?.country||'',source:p.lastLocationSource||'cloud'};try{const x=JSON.parse(localStorage.getItem(LOC_KEY)||'null');if(validPoint(x))return{lat:Number(x.lat),lon:Number(x.lon),city:x.homeCity||x.city||'',country:x.country||'',source:'saved-web'}}catch{}return null}
async function browserGeo(request=true){if(!navigator.geolocation)return null;let permission='prompt';try{permission=(await navigator.permissions?.query?.({name:'geolocation'}))?.state||'prompt'}catch{}if(!request&&permission!=='granted')return null;return new Promise(resolve=>navigator.geolocation.getCurrentPosition(async p=>resolve(await persistLocation({lat:p.coords.latitude,lon:p.coords.longitude},'web-gps')),()=>resolve(null),{enableHighAccuracy:false,timeout:9000,maximumAge:180000}))}
async function profileLocation(){const city=state.profile?.city||prefs().homeCity;if(!city)return null;try{const g=await Live.geocode(`${city}${state.profile?.country?`, ${state.profile.country}`:''}`);if(g&&validPoint(g)){const x={lat:g.lat,lon:g.lon,city,country:state.profile?.country||prefs().country||'',source:'profile'};try{localStorage.setItem(LOC_KEY,JSON.stringify(x))}catch{}return x}}catch{}return null}
async function bestLocation(request=false){const gps=await browserGeo(request);if(gps)return gps;const cloud=cloudLocation();if(cloud)return cloud;const profile=await profileLocation();if(profile)return profile;throw new Error('No location is available yet. Open LifeDashPro on your phone once with location enabled, or choose a city in Profile.')}
window.LifeDashLocation={best:bestLocation,refresh:()=>bestLocation(true),cloud:cloudLocation};
if(typeof Live!=='undefined'&&Live)Live.geo=()=>bestLocation(true);

/* Hide the redundant launcher/start button: the dock is now the launcher. */
function removeRedundantStart(){document.querySelectorAll('.desktop-start').forEach(x=>x.remove())}

/* One-click attachment open/download helpers. */
async function signed(path){return await D.signedUrl(path,3600)}
async function openAttachment(path){const u=await signed(path);window.open(u,'_blank','noopener,noreferrer')}
async function downloadAttachment(path,name='attachment'){const u=await signed(path);try{const r=await fetch(u);if(!r.ok)throw new Error('download');const blob=await r.blob(),obj=URL.createObjectURL(blob),a=document.createElement('a');a.href=obj;a.download=name||'attachment';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(obj),1500)}catch{window.open(u,'_blank','noopener,noreferrer')}}
try{attachmentsHtml=function(a){if(!a?.length)return'';return`<div class="attachment-list">${a.map(x=>`<div class="attachment"><div class="grow"><b>${esc(x.name)}</b><span>${x.size?`${Math.round(x.size/1024)} KB`:''}</span></div>${x.storagePath?`<button type="button" class="mini-btn" data-open-att="${esc(x.storagePath)}">Open</button><button type="button" class="mini-btn" data-download-att="${esc(x.storagePath)}" data-att-name="${esc(x.name||'attachment')}">Download</button>`:''}</div>`).join('')}</div>`}}catch{}
document.addEventListener('click',e=>{const d=e.target.closest('[data-download-att]');if(d){e.preventDefault();e.stopPropagation();downloadAttachment(d.dataset.downloadAtt,d.dataset.attName).catch(x=>toast(x.message||'Download failed',true));return}const o=e.target.closest('[data-open-att]');if(o){e.preventDefault();e.stopPropagation();openAttachment(o.dataset.openAtt).catch(x=>toast(x.message||'Open failed',true))}},true);

/* Finance history, based on Android v37.15 behavior. */
function changeMonth(delta){const raw=sessionStorage.getItem(FIN_KEY)||monthNow(),[y,m]=raw.split('-').map(Number),d=new Date(y,m-1+delta,1),next=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;if(next>monthNow())return;sessionStorage.setItem(FIN_KEY,next);render()}
try{financePage=function(){const tx=collection('finance_transactions'),bills=collection('finance_bills'),sel=sessionStorage.getItem(FIN_KEY)||monthNow();sessionStorage.setItem(FIN_KEY,sel);const m=tx.filter(x=>day(x.date).startsWith(sel)),inc=m.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.baseAmountAtEntry??x.amount??0),0),exp=m.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.baseAmountAtEntry??x.amount??0),0),label=new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(new Date(`${sel}-01T12:00:00`)),future=sel>=monthNow();return`${pageHead('Finance','Transactions, bills and monthly history share the Android sync model.',`<button class="quiet" data-fin-prev>‹</button><span class="pill">${esc(label)}</span><button class="quiet" data-fin-next ${future?'disabled':''}>›</button><button class="quiet" data-add-bill>＋ Bill</button><button class="primary" data-add-tx>＋ Transaction</button>`)}<div class="grid"><div class="card"><h3>Monthly balance</h3><div class="metric ${inc-exp>=0?'green':'red'}">${fmtMoney(inc-exp,state.profile?.currency||'EUR')}</div></div><div class="card"><h3>Income</h3><div class="metric green">${fmtMoney(inc,state.profile?.currency||'EUR')}</div></div><div class="card"><h3>Expenses</h3><div class="metric red">${fmtMoney(exp,state.profile?.currency||'EUR')}</div></div><div class="card span-8"><h3>Transactions · ${esc(label)}</h3>${txTable(m)}</div><div class="card"><h3>Upcoming bills</h3><div class="list">${bills.filter(x=>!x.isPaid).slice(0,10).map(x=>`<div class="list-item"><div class="grow"><b>${esc(x.title)}</b><span>${fmtDate(x.dueDate)} · ${fmtMoney(x.amount,x.currency)}</span></div><button class="mini-btn" data-edit-bill="${x.id}">Edit</button></div>`).join('')||'<span class="card-sub">No unpaid bills</span>'}</div></div></div>`}}catch{}
document.addEventListener('click',e=>{if(e.target.closest('[data-fin-prev]')){e.preventDefault();e.stopPropagation();changeMonth(-1)}if(e.target.closest('[data-fin-next]')){e.preventDefault();e.stopPropagation();changeMonth(1)}},true);

/* Bring attachments to Family and Vehicles as on Android. */
try{familyMemberModal=function(x={}){modal(x.id?'Edit member':'Family member',`<form id="fmForm" class="modal-form"><input type="hidden" name="id" value="${esc(x.id||id('member'))}"><label>Name<input required name="name" value="${esc(x.name||'')}"></label><div class="form-grid"><label>Relation<input name="relation" value="${esc(x.relation||'')}"></label><label>Birthday<input type="date" name="birthday" value="${esc(day(x.birthday))}"></label></div><label>Phone<input name="phone" value="${esc(x.phone||'')}"></label><label>Notes<textarea name="notes">${esc(x.notes||'')}</textarea></label><label>Attachment<input type="file" name="file"></label>${attachmentsHtml(x.attachments||[])}<div class="form-actions"><button class="quiet" type="button" data-close>Cancel</button><button class="primary">Save</button></div></form>`,root=>{$('#fmForm',root).onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,v=formData(f);let atts=[...(x.attachments||[])];try{if(f.file.files[0])atts.push(await D.upload('family',v.id,f.file.files[0]));await D.upsert('family_members',{...x,...v,attachments:atts,updatedAt:iso()});await reload('family_members');closeModal();toast('Family member synced');render()}catch(err){toast(err.message,true)}}})}}catch{}
try{familyTaskModal=function(x={}){modal(x.id?'Edit task':'Family task',`<form id="ftForm" class="modal-form"><input type="hidden" name="id" value="${esc(x.id||id('task'))}"><label>Task<input required name="title" value="${esc(x.title||'')}"></label><div class="form-grid"><label>Assigned to<input name="assignedTo" value="${esc(x.assignedTo||'')}"></label><label>Due date<input type="date" name="dueDate" value="${esc(day(x.dueDate))}"></label></div><label>Priority<select name="priority"><option>medium</option><option ${x.priority==='high'?'selected':''}>high</option><option ${x.priority==='low'?'selected':''}>low</option></select></label><label>Attachment<input type="file" name="file"></label>${attachmentsHtml(x.attachments||[])}<div class="form-actions"><button class="quiet" type="button" data-close>Cancel</button><button class="primary">Save</button></div></form>`,root=>{$('#ftForm',root).onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,v=formData(f);let atts=[...(x.attachments||[])];try{if(f.file.files[0])atts.push(await D.upload('family',v.id,f.file.files[0]));await D.upsert('family_tasks',{done:false,...x,...v,attachments:atts,updatedAt:iso()});await reload('family_tasks');closeModal();toast('Family task synced');render()}catch(err){toast(err.message,true)}}})}}catch{}
try{vehicleModal=function(v={}){modal(v.id?'Edit vehicle':'New vehicle',`<form id="vehForm" class="modal-form"><input type="hidden" name="id" value="${esc(v.id||id('vehicle'))}"><label>Name<input required name="name" value="${esc(v.name||'')}"></label><div class="form-grid"><label>Brand<input name="brand" value="${esc(v.brand||'')}"></label><label>Model<input name="model" value="${esc(v.model||'')}"></label></div><div class="form-grid"><label>Year<input type="number" name="year" value="${esc(v.year||'')}"></label><label>Plate<input name="licensePlate" value="${esc(v.licensePlate||'')}"></label></div><div class="form-grid"><label>Current km<input type="number" name="currentKm" value="${esc(v.currentKm||'')}"></label><label>Fuel<select name="fuelType">${['diesel','benzin','gas','elektro','hibrid'].map(x=>`<option ${v.fuelType===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="form-grid"><label>Insurance expires<input type="date" name="insuranceExpires" value="${esc(day(v.insuranceExpires))}"></label><label>Registration expires<input type="date" name="registrationExpires" value="${esc(day(v.registrationExpires))}"></label></div><label>Technical expires<input type="date" name="technicalExpires" value="${esc(day(v.technicalExpires))}"></label><label>Notes<textarea name="notes">${esc(v.notes||'')}</textarea></label><label>Attachment<input type="file" name="file"></label>${attachmentsHtml(v.attachments||[])}<div class="form-actions"><button class="quiet" type="button" data-close>Cancel</button><button class="primary">Save</button></div></form>`,root=>{$('#vehForm',root).onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,x=formData(f);let atts=[...(v.attachments||[])];try{if(f.file.files[0])atts.push(await D.upload('vehicles',x.id,f.file.files[0]));await D.upsert('vehicles',{services:[],fuelHistory:[],...v,...x,attachments:atts,year:x.year?Number(x.year):undefined,currentKm:x.currentKm?Number(x.currentKm):undefined,updatedAt:iso()});await reload('vehicles');closeModal();toast('Vehicle synced');render()}catch(err){toast(err.message,true)}}})}}catch{}
try{serviceModal=function(v){modal('Add service',`<form id="svcForm" class="modal-form"><input type="hidden" name="serviceId" value="${esc(id('svc'))}"><label>Type<select name="type"><option>small</option><option>big</option><option>fuel</option><option>tires</option><option>other</option></select></label><div class="form-grid"><label>Date<input type="date" name="date" value="${day(iso())}"></label><label>KM<input type="number" name="km"></label></div><label>Cost<input type="number" step="0.01" name="cost"></label><label>Notes<textarea name="notes"></textarea></label><label>Attachment<input type="file" name="file"></label><div class="form-actions"><button class="quiet" type="button" data-close>Cancel</button><button class="primary">Add service</button></div></form>`,root=>{$('#svcForm',root).onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,x=formData(f),sid=x.serviceId||id('svc');let atts=[];try{if(f.file.files[0])atts.push(await D.upload('vehicles',`${v.id}-${sid}`,f.file.files[0]));const svc={id:sid,type:x.type,date:x.date,km:Number(x.km||0),cost:Number(x.cost||0),notes:x.notes,attachments:atts};await D.upsert('vehicles',{...v,services:[...(v.services||[]),svc],currentKm:Math.max(Number(v.currentKm||0),Number(x.km||0)),updatedAt:iso()});await reload('vehicles');closeModal();toast('Service added');render()}catch(err){toast(err.message,true)}}})}}catch{}

/* Family Shared Space: clearer create/join state from Android v37.17. */
try{familyGroupModal=async function(){let groups=[];try{groups=await D.familyGroups()}catch{}modal('Family Shared Space',`<div class="modal-body"><div class="settings-card"><h3>${groups.length?'Connected shared space':'Create or join a shared space'}</h3><p class="card-sub">Family sharing uses Supabase RLS. To join another family, enter the invitation code created by that group.</p>${groups.map(g=>`<div class="list-item"><div class="grow"><b>${esc(g.name)}</b><span>Invitation code: <strong>${esc(g.share_code||'')}</strong></span></div></div>`).join('')||'<p class="card-sub">You are not currently in a shared group.</p>'}</div><div class="form-grid"><form id="createGroup" class="settings-card modal-form"><h3>Create</h3><label>Group name<input name="name" placeholder="My family"></label><button class="primary">Create secure group</button></form><form id="joinGroup" class="settings-card modal-form"><h3>Join</h3><label>Invitation code<input name="code" required maxlength="32" placeholder="Enter code"></label><button class="quiet">Join shared space</button></form></div></div>`,root=>{$('#createGroup',root).onsubmit=async e=>{e.preventDefault();try{const g=await D.createFamily(formData(e.currentTarget).name);toast(`Group created · ${g.share_code||''}`);closeModal()}catch(err){toast(err.message,true)}};$('#joinGroup',root).onsubmit=async e=>{e.preventDefault();try{await D.joinFamily(formData(e.currentTarget).code.trim());toast('Joined family shared space');closeModal()}catch(err){toast(err.message,true)}}})}}catch{}

/* Keep cloud location hydrated after sign-in/sync and refresh desktop weather from cloud fallback. */
async function hydrateLocation(){try{const p=cloudLocation()||await profileLocation();if(p){state.geo=p;const loc=document.getElementById('desktopLocation');if(loc)loc.textContent=p.city||p.country||'Synced location';const meta=document.getElementById('heroWeatherText');if(meta&&p.source==='cloud')meta.textContent='Using last synced mobile location';if(typeof Live!=='undefined'&&Live?.weather){const w=await Live.weather(p.lat,p.lon).catch(()=>null),c=w?.current;if(c){const t=Math.round(Number(c.temperature_2m));const ht=document.getElementById('heroTemp'),hw=document.getElementById('homeWeather'),hm=document.getElementById('homeWeatherMeta');if(ht)ht.textContent=`${t}°C`;if(hw)hw.textContent=`${t}°C`;if(hm)hm.textContent=`${p.city||'Synced location'} · cloud location fallback`}}}}catch{}}
const mo=new MutationObserver(()=>{removeRedundantStart();if(!document.getElementById('appView')?.classList.contains('hidden'))hydrateLocation()});
function init(){removeRedundantStart();mo.observe(document.body,{subtree:true,childList:true});setTimeout(hydrateLocation,500);setTimeout(hydrateLocation,1800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();